DROP SEQUENCE MYSEQ;
DROP TABLE MYBOARD;

--ALT + X : 실행 단축키
CREATE SEQUENCE MYSEQ NOCACHE;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(100) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD
VALUES(MYSEQ.NEXTVAL, '관리자','게시판 테스트','테스트 중입니다.
12345667ABCC',SYSDATE);

SELECT * FROM MYBOARD;

COMMIT;
--이클립스에서는 자동으로 커밋되기 때문에 커밋 실행해도 오류가 뜰 수밖에 없음.
--디벨로퍼 사용하는 사람들을 위해 적은 것.
