DROP TABLE PRODUCT_DETAIL;
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
	P_ID VARCHAR2(20) PRIMARY KEY,
	P_NAME VARCHAR2(20) NOT NULL,
	PRICE NUMBER NOT NULL,
	DES VARCHAR2(20)
);

INSERT INTO PRODUCT
VALUES('LT_SS13','삼성노트북',1570000,'갤럭시북 이온');
INSERT INTO PRODUCT
VALUES('LT_AP16', '애플노트북',38000000, 'MacbookPro16');
INSERT INTO PRODUCT
VALUES('PC_IBM21', 'IBMPC',750000, 'WINDOWS10');

SELECT * FROM PRODUCT;